[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_ark_foundation = "9sZpn4qSY2Xh5MEUbkFWxcJJaMwVePunGpxTNEtHkrtk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
