[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_ark_foundation = "BrJyMjrMFJEhjE3MQpAqbe7PMRCg5j9bE56SfRKyjNqE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "http://localhost:8898"
wallet = "~/.solana/.config/keypari.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test.validator]
url = "http://localhost:8898"