[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
fgg = "84A9QmWkUe8ZT1kWnQxBUiPNC5rL4KKW8XgQw8hPfCxe"

[registry]
url = "https://api.apr.dev"

# [provider]
# cluster = "Localnet"
# wallet = "~/.solana/.config/keypari.json"
[provider]
cluster = "https://api.devnet.solana.com"  # Use Devnet endpoint
wallet = "~/.solana/.config/keypari.json"  # Path to your wallet keypair

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
